In [1]:
import numpy as np

Latihan 2

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A, "\n")
#Lengkapi kodingan berikut
print('banyaknya entry = ', A.size)
print('dimensi array = ', A.ndim)
print('ukuran array = ', A.shape, "\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

banyaknya entry =  9
dimensi array =  2
ukuran array =  (3, 3) 



Latihan 3

In [3]:
#Lengkapi kodingan berikut
print('baris ke-3 =', A[2])
print('entry ke-1 & 2 baris ke-3 = ', A[2][0:2])
print('entry ke-2 & 3 kolom ke-3 = \n', A[1:3,2:]) #Baris 1-2 kolom >= 2

baris ke-3 = [7 8 9]
entry ke-1 & 2 baris ke-3 =  [7 8]
entry ke-2 & 3 kolom ke-3 = 
 [[6]
 [9]]


Latihan 4

In [4]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])
print("Hasil 2xA : \n", 2*A)
print("Hasil 2+A : \n", 2+A)
print("HasilA+B : \n", A+B)
print("HasilA-B : \n", A-B)
print("Hasil det(A) : \n ", np.linalg.det(A))

Hasil 2xA : 
 [[ 2  4]
 [14 16]]
Hasil 2+A : 
 [[ 3  4]
 [ 9 10]]
HasilA+B : 
 [[ 4  7]
 [ 8 14]]
HasilA-B : 
 [[-2 -3]
 [ 6  2]]
Hasil det(A) : 
  -6.0


In [5]:
#invers dari B, simpan jadi matriks D
D = np.linalg.inv(B)
print("D :\n",D, "\n")

#transpose D
print("D^T : \n", D.transpose(), "\n")

#nilai eigen dan vektor eigen dari A dan B
print("Eigen Value A :", np.linalg.eig(A)[0])
print("Eigen Vector A:\n", np.linalg.eig(A)[1],"\n")
print("Eigen Value B :", np.linalg.eig(B)[0])
print("Eigen Vector B:\n", np.linalg.eig(B)[1])

D :
 [[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]] 

D^T : 
 [[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]] 

Eigen Value A : [-0.62347538  9.62347538]
Eigen Vector A:
 [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]] 

Eigen Value B : [1.8074176 7.1925824]
Eigen Vector B:
 [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]


Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)?

In [6]:
print("BxD : \n",B*D)
print("BxD : \n",np.matmul(B,D))

BxD : 
 [[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]
BxD : 
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


Perbedaan perkalian entry yang dikalikan pada bilangan baris 1 di matriks B dikalikan bilangan pada baris 1 matriks D, akan tetapi pada kolom 2 matriks B akan dikalikan kolom 2 di matriks D. Sedangkan perkalian matriks yang dikalikan merupakan matrik baris B dengan kolom matrik D dan kolom matriks B dengan baris matrik D

---

